### ISSUE TITLE
Files include includes all sub-folders (v10-a14)

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#455]
```toml
[files]
include = [
    "*.dll",
]
```

```bash
Copying `"/releases/1.32.0.71/@tac_mods/tac_apollo_client.dll"` => "/home/jonpas/Work/Arma 3/Mods/TAC_Mods/.hemttout/build/releases/1.32.0.71/@tac_mods/tac_apollo_client.dll"
error: IO Error: No such file or directory (os error 2)
```
