### ISSUE TITLE
Files include subfolder not created and fails to copy (v10-a14)

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#460]
```toml
[files]
include = [
    "docs/README_*.md",
```

```bash
Copying `"/docs/README_PL.md"` => "/home/jonpas/Work/Arma 3/Mods/ACE3/.hemttout/build/docs/README_PL.md"
error: IO Error: No such file or directory (os error 2)
```

`.hemttout/build/docs` folder doesn't get created, so the copy of `README_PL.md` fails.
