### ISSUE TITLE
Feature Request - HEMTT launch multiple profiles

### ISSUE THREAD

**Issue by veteran29** [BrettMayson/HEMTT#511]
As an user I would like to have an option to quickly launch the game with different mods for testing:
```toml
# hemtt launch
[hemtt.launch]
workshop = [
    "450814997", # CBA_A3's Workshop ID
]

# hemtt launch trenches
[hemtt.launch.trenches]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "1224892496", # GRAD Trenches Workshop ID
]
```
