### ISSUE TITLE
Feature Request - Support HTML preset on hemtt.launch

### ISSUE THREAD

**Issue by JCalebBR** [BrettMayson/HEMTT#547]
As a developer for the Warhammer 40k scene, which is notorious for using 80 to 100+ mods per group, I find it way easier to deal with any incompatibilities with my mods by loading my group's entire modlist (~117 mods).
At the moment, achieving this through hemtt is rather tedious. Open html preset on browser, copy contents, parse contents via regex and output workshop id csv.
It would be very handy to have a preset option under hemtt.launch, which would take care of all of that for the user.

**Comment by JCalebBR** [comment]
Example:
```toml
[hemtt.launch.nameOfPreset]
preset = "nameOfPresetFile" # .html implied, perhaps inside a presets folder for further organization
```
