### ISSUE TITLE
Not loading presets on launch

### ISSUE THREAD

**Issue by DartRuffian** [BrettMayson/HEMTT#600]
HEMTT does not load mods from `presets` when launching. If the Steam Workshop ids are placed in `workshop` they (down)load and are added to the startup parameters like normal. [Veteran29 also replicated the issue on their end](https://ptb.discord.com/channels/976165959041679380/1039189045655392389/1171219404164452515).

---

HEMTT Version: `1.10.0`
[HTML Modlist (Pastebin)](https://pastebin.com/DVkvLADK). Located at `.hemtt\presets\main.html`
Launch Properties:
```toml
[hemtt.launch.default]
workshop = []
presets = [
    "main"
]
dlc = []
optionals = []
parameters = []
```

Launching with `hemtt.exe launch`.
