### ISSUE TITLE
Using linting options in both lints.toml and project.toml will make project.toml options be ignored

### ISSUE THREAD

**Issue by diwako** [BrettMayson/HEMTT#885]
**Tools (complete and add to the following information):**
- **HEMTT:** `1.14.2`
- **Operating System:** Windows

**Description:**
Adding linting options into both the `project.toml` and `lints.toml` will cause the options in the `project.toml` to be ignored.
In general, this is the correct handling, but hemtt should log out that there are conflicting configuration sources.

To cause the issue, have this in the `project.toml`
```toml
[lints.stringtables.sorted]
options.only-lang = true
```

And this in the `lints.toml`
```toml
[sqf.var_all_caps]
enabled = true
options.ignore = [
    "ACRE_IS_SPECTATOR"
]
```

Note that the options are NOT overlapping.

Current repo that is worked on is this: https://github.com/diwako/diwako_dui/tree/linecompass
branch: `linecompass`

Note: no `lints.toml` in project, issue was found when playing around with the file.

**Steps to reproduce:**

1. Use DUI project with linting options mentioned above in both files (uncomment `lints.sqf.var_all_caps` in `project.toml`)
2. Run `hemtt dev`
3. see `4 stringtables are not sorted` message, `project.toml` linting option is ignored
4. Have conflicting/duplicate options in both files
5. See conflict message with typo of word `conflct`

**Expected behavior:**
Hemtt telling me to use one or the other file for linting options, even on none conflicting/duplicate options
