### ISSUE TITLE
Feature Request - Ignore list for unused stringtable keys

### ISSUE THREAD

**Issue by R3voA3** [BrettMayson/HEMTT#942]
While I like the function it's currently quite limited and produces a lot of false positives when stringtable keys are generated via script and are therefore not found anywhere in config.

Example:

Key definition in stringtable.xml
str_enh_main_damage_light_1_hitpoint 

Usage in script
```sqf
private _name = format ["%1_%2_%3_%4_%5", "STR", "ENH", "MAIN", "DAMAGE", toUpper _x]; //String is build like this to prevent error when checking for missing strings
```
So what I'd like to see is an ignore list so I could blacklist "STR_ENH_MAIN_DAMAGE_" from being flagged as not used.

```
[lints.localization]
options.ignore = [
    "STR_ENH_MAIN_DAMAGE_*"
]
```

**Comment by BrettMayson** [comment]
https://hemtt.dev/lints/stringtables#usage

`ignore` supports regex or just `*`

```toml
[lints.stringtables.usage]
options.ignore = [
    "str_myproject_pre*",
]
options.ignore_unused = true
```
