### ISSUE TITLE
Feature Request - Add `author()` to project library

### ISSUE THREAD

**Issue by DartRuffian** [BrettMayson/HEMTT#970]
Add a `author()` method to the [Project library](https://hemtt.dev/rhai/library/project.html). The rest of the main project.toml properties are included, but not `author`.

E.g.
```toml
# project.toml
name = "My Mod"
author = "Splendid Modder"
prefix = "mymd"
mainprefix = "z"
```

```js
HEMTT.project().name(); // "My Mod"
HEMTT.project().author(); // "Splendid Modder"
HEMTT.project().prefix(); // "mymd"
HEMTT.project().mainprefix(); // "z"
```
